In [2]:
import numpy as np

### Ejercicio 1

In [3]:
A = np.array([[1,4],[-1,3],[2,-9]])
cero= np.zeros((3,2))
r=A-A
print(r)

[[0 0]
 [0 0]
 [0 0]]


### Ejercicio 2

In [4]:
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])
r = A@B
print(r) 

[[12 -6  3]
 [-4 12 14]]


### Ejercicio 3

In [5]:
res = np.array([[30, 15, 4],[25, 18, 8]])
cntr= np.array([[1.2, 2.2, 4.5],[1.3, 2.1, 4.6]])

print(cntr.T)

r=res@cntr.T
print(r)

print(f"Tienda 1, {(r[0,0]+r[1,1])}")
print(f"Tienda 2, {(r[0,1]+r[1,1])}")

[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
[[ 87.   88.9]
 [105.6 107.1]]
Tienda 1, 194.10000000000002
Tienda 2, 196.0


### Ejercicio 4

In [31]:
productos = np.array([[200,75],[150,100],[100,125]])
precios = np.array([[1.5,1.75],[1,1.5],[2,1]])
print('Unidades de productos (<almacenes> , <productos>)')
print(productos)
print(productos.shape)
print('Precios por unidad ([camion , tren] , <productos>)')
print(precios)

porCamion=productos*np.array(precios[:,0:1])
porTren=productos*np.array(precios[:,1:2])
print('Precios en camión (<almacenes>,<productos>)')
print(porCamion)
print(f"Total = {porCamion.sum()}")
print('Precios en tren (<almacenes>,<productos>)')
print(porTren)
print(f"Total = {porTren.sum()}")

if (porCamion.sum() < porTren.sum()):
    barato = "camión"
    caro = "tren"
else:
    barato="tren"
    caro="camión" 


print(f"Es más barato transportarlo por {barato}, que por {caro}")



Unidades de productos (<almacenes> , <productos>)
[[200  75]
 [150 100]
 [100 125]]
(3, 2)
Precios por unidad ([camion , tren] , <productos>)
[[1.5  1.75]
 [1.   1.5 ]
 [2.   1.  ]]
Precios en camión (<almacenes>,<productos>)
[[300.  112.5]
 [150.  100. ]
 [200.  250. ]]
Total = 1112.5
Precios en tren (<almacenes>,<productos>)
[[350.   131.25]
 [225.   150.  ]
 [100.   125.  ]]
Total = 1081.25
Es más barato transportarlo por tren, que por camión


### Ejercicio 5

In [7]:
a=np.array([[3,2],[6,4]])
b=np.array([6,-9])

print('Si lo corremos nos dice que es una matriz singular, esto es porque el sistema no tiene solución')

#sistema1 = np.linalg.solve(a,b)
#print(sistema1)
#print(a@sistema1)



Si lo corremos nos dice que es una matriz singular, esto es porque el sistema no tiene solución


In [8]:
#sistema2 = np.array([[1,1,3],[1,-4,1]])
a=np.array([[1,1],[1,-4]])
b=np.array([3,1])
sistema2 = np.linalg.solve(a,b)
print("Solución: ",sistema2)
print(a@sistema2)
print(f"x = {sistema2[0]}   y = {sistema2[1]}")

Solución:  [2.6 0.4]
[3. 1.]
x = 2.6   y = 0.4


In [9]:
#sistema3 = np.array([[2,-1,2,3],[2,3,-1,0],[1,2,2,-12]])

a=np.array([[2,-1,2],[2,3,-1],[1,2,2]])
b=np.array([3,0,-12])
sistema3 = np.linalg.solve(a,b)
print("Solucion: ", sistema3)
print(a@sistema3)
print(f"x = {sistema3[0]}   y = {sistema3[1]}   z= {sistema3[2]}")

Solucion:  [ 3.65217391 -3.7826087  -4.04347826]
[ 3.0000000e+00  8.8817842e-16 -1.2000000e+01]
x = 3.6521739130434785   y = -3.782608695652174   z= -4.043478260869565
